module.exports = {
	200: 'Success.',
	300: 'Email address already exists, please try someting different',    
	400: 'Bad Request.',
    401: 'Invalid user creation, please contact administration',
	404: 'Order not found!',

	SUCCESS_PASSWORD: 'Password changed successfully.',
	201: 'Invalid access token.',
	402: 'Your account is locked, please contact to administration',
	403: 'User is admin',
    405: 'Validation Error.',
	408: 'Token already expired.',
	409: 'Password expired, please change you password again!',
	410: 'Password used previously, please enter new one!',
	411: 'Please contact to administration, something went wrong during password change!',
	412: 'Old password is incorrect, please check and try again',
	413: ' Codes type is not exist, please contact to administartion!',
	414: 'Invalid shift date, please select today date!',
	415: 'Inappropriate shift code have selected, please select valid shift code!',
	416: 'Invalid engineer email id, please provide registered email id only!',
	417: 'User already checked in!',
	418: 'Invalid credenrial for shift code, please contact administration!',
	419: 'Location not found, please contact to administration!',
	420: 'Role not found, please contact to administration!',
	421: 'Not able to update shift attendance, please contact to administrator!',	
	422: 'Shift attendace already present, please try something different',
	423: 'Failed to update shift, please contact administrator!',
	424: 'Shift log failed to update, please contact administrator!',
	425: 'Failed to fetch facility, please contact administrator!',
	426: 'No Sub facility data found!',
	427: 'No Equipment data found!',
	428: 'No Sub Equipment data found!',
	429: 'Please check in your shift attendance must!',
	430: 'Invalid Gas date, please select today date!',
	431: 'Invalid eLogbook data provided, please contact administrator!',
	432: 'No data found in e-logbook!',
	433: 'Faild to update elogbook, please try again with valid engineer email id!',
	434: 'Failed to update elogbook, please contact administrator!',
	435: 'ELogbook failed to update log, please contact administrator!',
	436: 'Faild to create instruction, please contact administrator!',
	437: 'Type of instruction is already creaded by login mudule, please update it if you want to alter!',
	438: 'No Instruction found, please send valid module id and engineer email id!',
	439: 'No such data where found to delete, please pass valid data to delete!',
	440: 'No instruction data found, please send valid source id!',
	441: 'Failed to update instruction, please contact administrator!',
	442: 'No report found!',
	443: 'No pump record found!',
	444: 'Failed to create equipment run hour,please contact administrator!',
	445: 'Pump Parameter Already Exists!',
	446: 'Faild to update equipment run hour parameter data, please contact to administrator!',
	447: 'No Data Found!',
	448: "Faild to create daily check list, please contact to administrator!",
	449: "Check list already exists!",
	450: "Faild to update daily check list parameter data, please contact to administrator!",
	451: "No Instruction found!",
	452: "No Pipeline data found, please contact to administrator!",
	453: "No Incident record found!",
	454: "No Logsheet Type found!",
	455: "Failed to create Logsheet, please contact to administrator!",
	456: "Existing Logsheet Found!",
	457: "Failed to update logsheet!, please contact to administrator!",
	458: 'Role Not Found, please contact to administrator!',
    500: 'Some unexpected internal server error occurred.',
}